---
title: "Developing Data Products - Assignment Week 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 11 September 2019


```{r, eval=TRUE, echo = TRUE, message=FALSE}
library(leaflet)
set.seed(12345)

my_map <- data.frame(name = c("place 1","place 2", "place 3", "place 4", "place 5", "place 6", "place 7", "place 8", "place 9", "place 10"),
                    lat=runif(10, min=51.4, max=51.6), 
                    lng=runif(10, min=-0.1, max=0.2),
                    col = sample(c("red","orange","yellow"), 10, replace=TRUE),
                    stringAsFactors=FALSE)


my_map %>% leaflet() %>% 
          addTiles() %>%
          addCircleMarkers(weight =5, 
                           popup = my_map$name, 
                           color=my_map$col,
                           clusterOption=markerClusterOptions()) %>%
          addLegend(labels=LETTERS[1:3], 
                    colors=c("red","orange","yellow"))
```